import React from "react";
import Tab from 'react-bootstrap/Tab';
import Tabs from 'react-bootstrap/Tabs';
import './Home.css';
import ResponsiveGIF from "../../components/ResponsiveGIF/ResponsiveGIF";
import Describer from "../../components/Describer/Describer";

const descriptions = [
    {header: "What is OpenAI Sora?", body: "[Generated by OpenAI ChatGPT] OpenAI's Sora is an advanced generative AI model designed to create realistic \n" +
            " and imaginative videos from text prompts. Unveiled in February 2024, Sora can generate videos up to 60 seconds long, \n" +
            " featuring complex scenes, dynamic camera movements, and expressive characters. \n" +
            " It utilizes a diffusion transformer architecture, similar to that of DALL·E 3, allowing it to produce high-quality, coherent video content from textual descriptions ."},

    {header: "Prompt", body: "A Programmer sitting in front of the desk with multiple screens in the clouds\n" +
            " with the sun shining. The camera should see the hands typing fast on the keyboard.\n" +
            " The theme should have something superhuman Artificial Intelligence powers going on."}
]

const Home: React.FC = () => {
    return (
        <div className="padding">
                <Tabs variant="tabs" defaultActiveKey="openai" className="custome-tabs">
                    <Tab eventKey="openai" title="OpenAI Sora">
                        <ResponsiveGIF
                            src="sora-ai-programmer2.gif"
                            header="OpenAI Sora: Video (GIF)"/>
                        <Describer items={descriptions} />
                    </Tab>
                    <Tab eventKey="pictory" title="Pictory.ai" className="tab-inactive">
                        <h4>Pictory.ai</h4>
                        <p>Content for Pictory.ai goes here.</p>
                    </Tab>
                </Tabs>
        <div />
    </div>
    );
};

export default Home