import React from "react";
import Tab from 'react-bootstrap/Tab';
import Tabs from 'react-bootstrap/Tabs';
import './Home.css';
import ResponsiveGIF from "../../components/ResponsiveGIF/ResponsiveGIF";
import Describer from "../../components/Describer/Describer";


const Home: React.FC = () => {
    return (
        <div className="padding">
                <Tabs variant="tabs" defaultActiveKey="openai" className="custome-tabs">
                    <Tab eventKey="openai" title="OpenAI Sora">
                        <ResponsiveGIF
                            src="sora-ai-programmer2.gif"
                            header="OpenAI Sora: Video (GIF)"/>
                        <Describer items={openAIdescriptions} />
                    </Tab>
                    <Tab eventKey="pictory" title="Pictory.ai" className="tab-inactive">
                        <div className="video-caption">Pictory.ai: Generated video from URL asla.no/background</div>
                        <video controls width="100%" height="auto">
                            <source src="/videos/pictory480.mp4" type="video/mp4" />
                            Your browser does not support the video tag.
                        </video>
                        <Describer items={pictoryAIDescriptions} />
                    </Tab>
                    <Tab eventKey="canva" title="Canva">
                        <ResponsiveGIF src="canva.png" header="First slide from https://petter.my.canva.site/"/>
                        <Describer items={canvaDescription} />
                    </Tab>
                </Tabs>
        <div />
    </div>
    );
};

export default Home

const openAIdescriptions = [
    {header: "What is OpenAI Sora?", body: "*Generated by OpenAI ChatGPT*\n" +
            "\n" +
            "**OpenAI's Sora** is an advanced generative AI model designed to create realistic  \n" +
            "and imaginative videos from text prompts.\n" +
            "\n" +
            "Unveiled in **February 2024**, Sora can generate videos up to **60 seconds** long,  \n" +
            "featuring **complex scenes**, **dynamic camera movements**, and **expressive characters**.\n" +
            "\n" +
            "It utilizes a **diffusion transformer architecture**, similar to that of **DALL·E 3**,  \n" +
            "allowing it to produce high-quality, coherent video content from textual OpenAI descriptions.\n" },

    {header: "Prompt", body: "A Programmer sitting in front of the desk with multiple screens in the clouds\n" +
            " with the sun shining. The camera should see the hands typing fast on the keyboard.\n" +
            " The theme should have something superhuman Artificial Intelligence powers going on."}
]

const pictoryAIDescriptions = [
    {header: "What is Pictory.ai", body: "**Pictory.ai** is an AI-powered video creation and editing platform designed to \n" +
            " help users transform text-based content into professional-quality videos quickly and easily. \n\n" +
            " For this purpose, I used the 'URL to Video' feature, referencing my Background url: https://asla.no/background \n" +
            " This feature creates a summary about the content of the page, and generates small suitable videos based on the content \n" +
            " and put them together. You may add features like subtitles, 'text to speech' and more. "},
    {header: "URL to Video feature", body: "" +
            "### Petter Fagerlund: Mastering IT Solutions with Artificial Intelligence\n" +
            "\n" +
            "Have you ever wondered how technology shapes our daily lives? Meet **Petter Fagerlund**, a seasoned IT expert.  \n" +
            "\n" +
            "Born and raised in **Hamar**, Petter returned home after gaining his *sivilingeniør* degree in **Datateknikk from NTNU Trondheim** and a year in **San Diego**. He began his career in **Oslo**, working as a consultant before family ties brought him back to Hamar.  \n" +
            "\n" +
            "Petter thrives on tackling IT challenges daily. Currently, he leads the **Dovre Project**, transforming **NorgesGruppen's core system**. Here, he adapts data management for clients and suppliers using **Azure tools**, **Java EE**, and more.  \n" +
            "\n" +
            "In his previous startup role, he automated **invoicing processes**, integrating booking and accounting systems using **AWS** and **GitHub Actions**. Petter's journey encompasses roles in **payment services** and **API development**, where he enhanced customer transactions with platforms like **Vipps** and **Apple Pay**.  \n" +
            "\n" +
            "His expertise doesn’t stop there; he also optimized older **database APIs** to better serve clients. As a senior consultant, he revamped **NorgesGruppen's financial system**, building a modern web solution with **React/Redux**.  \n" +
            "\n" +
            "With a passion for **technology**, **football**, and **golf**, Petter seamlessly combines interests with expert programming, utilizing **artificial intelligence** to elevate solutions.  \n" +
            "\n" +
            "**Get inspired by Petter's journey and explore the future of IT innovation today!**\n"}
]

const canvaDescription = [
    {header: "What is Canva?", body: "Canva is an online platform that helps with visual design and document creation " +
            "like slides, presentations, short videos with additional AI features to help speed up the process."},
    {header: "Slide Presentation", body: "For this project I needed a slide presentation for the parents in 1st grade " +
            "that was easily available independent of device. I described the scenario and Canva suggested multiple" +
            " slide themes in addition to multiple pictures and short videos. Have a look at https://petter.my.canva.site/ "}
]